
# echo -n "<your-access-key-id>" | base64
# echo -n "<your-application-key>" | base64


apiVersion: v1
kind: Secret
metadata:
  name: b2-backup-secret
  namespace: databases  # Ensure this matches your namespace
type: Opaque
data:  # Using 'data' since values are base64 encoded
  B2_ACCESS_KEY_ID: MDA1ZWJlMGY3MDEwYzU1MDAwMDAwMDAwNQ==          # Paste the base64-encoded Access Key ID
  B2_APPLICATION_KEY: SzAwNTlaY29jV3JyMWUwNVQ2ejRsVE5nTG5rTTkzVQ== # Paste the base64-encoded Application Key

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup-owner
  namespace: databases

---

apiVersion: moco.cybozu.com/v1beta2
kind: BackupPolicy
metadata:
  namespace: databases
  name: moco-backups
spec:
  # Backup schedule.  Any CRON format is allowed.
  schedule: "0 3 * * 1"

  jobConfig:
    # An existing ServiceAccount name is required.
    serviceAccountName: backup-owner
    env:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: b2-backup-secret
          key: B2_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: b2-backup-secret
          key: B2_APPLICATION_KEY

    bucketConfig:
      bucketName: markitectos-moco-mysql-cluster   # Replace with your B2 bucket name
      region: "us-east-005"               # Backblaze's S3-compatible region
      endpointURL: "https://s3.us-east-005.backblazeb2.com"  # Backblaze S3 endpoint
      usePathStyle: true

    workVolume:
      emptyDir: {}