apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: user
spec:
  # If you want the user to be created with a different name than the resource name
  # name: user-custom
  mariaDbRef:
    name: mariadb-galera
  passwordSecretKeyRef:
    name: mariadb-gal-op-t2-db-pass
    key: password
  # This field is immutable and defaults to 10
  maxUserConnections: 20
  host: "%"
  retryInterval: 5s
