## To create the password value in base 64 to set this secret
# echo -n '<your_password>' | base64
apiVersion: v1
kind: Secret
metadata:
  name: valkey-password
  namespace: cache
type: Opaque
data:
  valkey-password: cksjVzR3Jm40bjJKXnI5Q1dEVA==


