apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: n8n-ingressroute
  namespace: automation
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`n.markitectos.com`)
      kind: Rule
      services:
        - name: n8n
          port: 80
  tls:
    secretName: n8n-tls