apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: raid-ssd-cached-local-path
provisioner: rancher.io/local-path
parameters:
  nodePath: /mnt/raid-ssd-cached
  pathPattern: "{{ .PVC.Namespace }}/{{ .PVC.Name }}"
allowedTopologies:
- matchLabelExpressions:
  - key: disk-type-raid-ssd-cached
    values:
    - "true"
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: true