# Allowed values: standalone or high-availability
architecture: "high-availability"
# replicaCount: 3

nodeSelector:
  kubernetes.io/arch: amd64

# Autoscaling  (requires architecture: "high-availability")
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPU: 10
  targetMemory: 10

service:
  type: ClusterIP
  port: 11211

networkPolicy:
  enabled: true
  allowExternal: false
  ingressNSMatchLabels:
    access-memcached: "true"
  ingressPodMatchLabels:
    access-memcached: "true"

## @param podAntiAffinityPreset Pod anti-affinity preset. Ignored if `affinity` is set. Allowed values: `soft` or `hard`
## Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
##
podAntiAffinityPreset: soft

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 3
    memory: 2048Mi

metrics:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 1
      memory: 128Mi

persistence:
  enabled: false
