{{- if $.Values.SSLCert.enabled }}
{{- range .Values.global.domain.names }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ . | replace "." "-" }}-{{ if $.Values.SSLCert.productionReady }}prod{{ else }}staging{{ end }}-certificate
  namespace: {{ $.Release.Namespace }}
  annotations:
    {{- if $.Values.SSLCert.keepOnUninstall }}
    helm.sh/resource-policy: keep
    {{- end }}
spec:
  secretName: {{ . | replace "." "-" }}-{{ if $.Values.SSLCert.productionReady }}prod{{ else }}staging{{ end }}-ssl-secret
  issuerRef:
    {{- if $.Values.SSLCert.productionReady }}
    name: letsencrypt-production
    {{- else }}
    name: letsencrypt-staging
    {{- end }}
    kind: ClusterIssuer
  dnsNames:
    - {{ . }}
{{- end }}
{{- end }}