apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-mautic-configmap
data:
  MAUTIC_DB_HOST: "{{ .Values.database.primaryHost }}"
  # MAUTIC_DB_HOST_RO: "{{ .Values.database.replicaHost }}"
  MAUTIC_DB_PORT: "{{ .Values.database.port }}"
  # MAUTIC_DB_TABLE_PREFIX: "{{ .Values.database.table_prefix }}"
  MAUTIC_DB_DATABASE: "{{ .Values.database.dbName }}"
  MAUTIC_DB_USER: "{{ .Values.database.username }}"

  MAUTIC_MESSENGER_DSN_EMAIL: "doctrine://default"
  MAUTIC_MESSENGER_DSN_HIT: "doctrine://default"
  DOCKER_MAUTIC_RUN_MIGRATIONS: "false"
  DOCKER_MAUTIC_LOAD_TEST_DATA: "false"