apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-custom-parameters-local
data:
  parameters_local.php: |
    <?php
    $parameters = array(

        'db_host' => '{{ .Values.database.primaryHost }}',
        'db_host_ro' => '{{ .Values.database.replicaHost }}',
        'db_port' => '{{ .Values.database.port }}',
        'db_name' => '{{ .Values.database.dbName }}',
        'db_user' => '{{ .Values.database.username }}',
        'db_table_prefix' => '{{ .Values.database.table_prefix }}',
        'debug' => true
    );
