apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mautic-worker
spec:
  replicas: {{ .Values.mautic.worker.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mautic-worker
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mautic-worker
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            {{- if $.Values.global.preferToRunOnAMD64 }}
            - weight: 90
              preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
            {{- end }}
            {{- if $.Values.global.preferNodeR913thenR912 }}
            - weight: 80
              preference:
                matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                  - r9-13
            - weight: 50
              preference:
                matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                  - r9-12
            {{- end }}
        {{- if $.Values.global.preferToDistributePods }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ .Release.Name }}-mautic-worker
                topologyKey: "kubernetes.io/hostname"
        {{- end }}
      volumes:
        # - name: custom-mautic-config
        #   configMap:
        #     name: {{ $.Release.Name }}-custom-parameters-local
        {{- if .Values.externalPVC.enabled }}
        - name: mautic-data-pvc
          persistentVolumeClaim:
            claimName: {{ $.Values.externalPVC.pvcName }}
        {{- else }}
        {{- if .Values.persistence.enabled }}
        - name: mautic-data-pvc
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-mautic-data-pvc
        {{- end }}
        {{- end }}
      # initContainers:
      # - name: copy-defaults
      #   image: "{{ .Values.mautic.image.repository }}:{{ .Values.mautic.image.tag }}"
      #   command: ["/bin/sh", "-c"]
      #   args:
      #     - |
      #       if [ -z "$(ls -A /mnt/plugins)" ]; then
      #         cp -rn /var/www/html/docroot/plugins/* /mnt/plugins
      #         chown -R 82:82 /mnt/plugins
      #       fi
      #       if [ -z "$(ls -A /mnt/themes)" ]; then
      #         cp -rn /var/www/html/docroot/themes/* /mnt/themes
      #         chown -R 82:82 /mnt/plugins
      #       fi
      #   volumeMounts:
      #     - name: mautic-data-pvc
      #       mountPath: /mnt/plugins
      #       subPath: plugins
      #     - name: mautic-data-pvc
      #       mountPath: /mnt/themes
      #       subPath: themes
      containers:
      - name: mautic-worker
        image: "{{ .Values.mautic.image.repository }}:{{ .Values.mautic.image.tag }}"
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - 'pgrep supervisord && pgrep -f "messenger:consume"'
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - 'pgrep supervisord && pgrep -f "messenger:consume"'
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            cpu: {{ .Values.mautic.worker.resources.requests.cpu }}
            memory: {{ .Values.mautic.worker.resources.requests.memory }}
          limits:
            cpu: {{ .Values.mautic.worker.resources.limits.cpu }}
            memory: {{ .Values.mautic.worker.resources.limits.memory }}
        volumeMounts:
          # - name: custom-mautic-config
          #   mountPath: /var/www/html/config/parameters_local.php
          #   subPath: parameters_local.php
          {{- if or .Values.persistence.enabled .Values.externalPVC.enabled }}
          - name: mautic-data-pvc
            mountPath: /var/www/html/config
            subPath: config
          - name: mautic-data-pvc
            mountPath: /var/www/html/var/logs
            subPath: logs
          - name: mautic-data-pvc
            mountPath: /var/www/html/docroot/media/files
            subPath: media/files
          - name: mautic-data-pvc
            mountPath: /var/www/html/docroot/media/images
            subPath: media/images
          - name: mautic-data-pvc
            mountPath: /var/www/html/docroot/plugins
            subPath: plugins
          - name: mautic-data-pvc
            mountPath: /var/www/html/docroot/themes
            subPath: themes
          - name: mautic-data-pvc
            mountPath: /var/www/html/docroot/translations
            subPath: translations                                    
          - name: mautic-data-pvc
            mountPath: /opt/mautic/cron
            subPath: cron
          {{- end }}
        envFrom:
          - configMapRef:
              name: {{ $.Release.Name }}-mautic-configmap          
        env:
          - name: DOCKER_MAUTIC_ROLE
            value: mautic_worker
          - name: MAUTIC_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ $.Release.Name }}-db-pass
                key: password          