{{- if $.Values.mautic.web.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $.Release.Name }}-hpa-mautic-web  
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-mautic-web
  minReplicas: {{ $.Values.mautic.web.autoscaling.minReplicas }}
  maxReplicas: {{ $.Values.mautic.web.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ $.Values.mautic.web.autoscaling.targetCPUUtilization }}
{{- end }}