{{- if $.Values.ingressRoute.enabled }}
{{- range .Values.global.domain.names }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ . | replace "." "-" }}-default-headers
  namespace: {{ $.Release.Namespace }}
spec:
  headers:
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 15552000
    customFrameOptionsValue: SAMEORIGIN
    customRequestHeaders:
      X-Forwarded-Proto: https
{{- end }}
{{- end }}