apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $.Release.Name }}-pdb-mautic-worker
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mautic-worker