{{- if not .Values.externalPVC.enabled }}
{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mautic-data-pvc
  annotations:
    {{- if $.Values.persistence.keepOnUninstall }}
    helm.sh/resource-policy: keep
    {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessModes | quote }}
{{- if .Values.persistence.storageClassName }}
  {{- if (eq "-" .Values.persistence.storageClassName) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}
{{- end }}