## To create the password value in base 64 to set this secret
# echo -n '<your_password>' | base64

## Sets the Secret Password for the DB on the namespace of the DB and the namespace of the application

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-db-pass
  namespace: {{ .Values.database.namespace }}
type: Opaque
data:
  password: {{ .Values.database.secretPasswordKey }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-db-pass
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  password: {{ .Values.database.secretPasswordKey }}