apiVersion: v1
kind: Secret
metadata:
  name: mautic-db-credentials
type: Opaque
stringData:
  db-host: {{ .Values.mautic.database.host }}
  db-name: {{ .Values.mautic.database.name }}
  # Add other database credentials securely