apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mautic-web
  labels:
    app: mautic-web
spec:
  selector:
    app: mautic-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP