apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mautic-web
  labels:
    app: {{ .Release.Name }}-mautic-web
spec:
  selector:
    app: {{ .Release.Name }}-mautic-web
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 9000
      protocol: TCP
      targetPort: 9000
  type: ClusterIP
  sessionAffinity: None