version: "2.4"
services:
  minio:
    image: tobi312/minio:alpine-RELEASE.2024-09-22T00-33-43Z
    container_name: minio
    restart: unless-stopped
    expose:
      - "9000"
      - "9001"
    volumes:
      - ./minio-data:/data:rw
    environment:
      MINIO_ROOT_USER: maxitromer
      MINIO_ROOT_PASSWORD: PgBqk4UE4h#C63@av2%6JAyp*28&l
    command: ["server", "--address", ":9000", "--console-address", ":9001", "/data"]
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:9000/minio/health/live"]
      interval: 60s
      timeout: 10s
      retries: 3
  cloudflared:
    image: erisamoe/cloudflared:2024.9.1
    restart: unless-stopped
    container_name: cloudflared
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    depends_on:
      - minio