apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: m2-local-path
provisioner: rancher.io/local-path
parameters:
  nodePath: /mnt/m2
  pathPattern: "{{ .PVC.Namespace }}/{{ .PVC.Name }}"
allowedTopologies:
- matchLabelExpressions:
  - key: disk-type-m2
    values:
    - "true"
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: true