# Encode your values in Base64. You can do this in the terminal:
# echo -n 'your-user' | base64
# echo -n 'your-password' | base64
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
type: Opaque
data:
  admin-user: bWF4aXRyb21lcg==  # Base64 encoded
  admin-password: cjkqNjliUnZ6YjJSQFJkKkFLcQ==  # Base64 encoded