global:
  domain:
    names: 
      - t5.markitectos.com

# Traefik IngressRoute Configuration
traefik:
  ingressRoute:
    enabled: true

SSLCert:
  enabled: true
  productionReady: false  # on false will use letsencrypt-staging
  keepOnUninstall: false


mautic:
  # Mautic container configurations
  image:
    repository: mautic/mautic
    tag: 5-apache
    pullPolicy: IfNotPresent

  # Different deployment types
  web:
    replicaCount: 2
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1
        memory: 2Gi

  cron:
    replicaCount: 1
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

  worker:
    replicaCount: 3
    resources:
      requests:
        cpu: 300m
        memory: 756Mi
      limits:
        cpu: 750m
        memory: 1.5Gi

  # Redis Configuration for Sessions and Caching
  # redis:
  #   enabled: true
  #   host: redis-cluster.cache.svc.cluster.local
  #   port: 6379

# Persistent Volumes Configuration with Longhorn
persistence:
  enabled: true
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  size: 10Gi

database:
  namespace: databases
  clusterName: mysql-cluster
  primaryHost: moco-mysql-cluster-primary.databases.svc.cluster.local
  primaryPort: 3306
  replicaHost: moco-mysql-cluster-replica.databases.svc.cluster.local
  replicaPort: 3306
  dbName: t5_database
  username: t5_user
  secretPasswordKey: U2dZSmYrTnljRXM5cVY4eA==
  # actual password: SgYJf+NycEs9qVix