global:
  preferNodeR913thenR912: false
  preferToDistributePods: true
  preferToRunOnAMD64: true
  domain:
    names: 
      - t5.markitectos.com

# Traefik IngressRoute Configuration
traefik:
  ingressRoute:
    enabled: true

SSLCert:
  enabled: true
  productionReady: false  # on false will use letsencrypt-staging
  keepOnUninstall: false


mautic:
  # Mautic container configurations
  image:
    repository: mautic/mautic
    tag: 5.1.1-apache
    pullPolicy: IfNotPresent

  # Different deployment types
  web:
    replicaCount: 1
    autoscaling:
      enabled: false
      minReplicas: 2
      maxReplicas: 6
      targetCPUUtilization: 70
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1
        memory: 2Gi

  cron:
    replicaCount: 1
    autoscaling:
      enabled: false
      minReplicas: 2
      maxReplicas: 6
      targetCPUUtilization: 70
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

  worker:
    replicaCount: 1
    autoscaling:
      enabled: false
      minReplicas: 2
      maxReplicas: 6
      targetCPUUtilization: 70
    resources:
      requests:
        cpu: 300m
        memory: 756Mi
      limits:
        cpu: 750m
        memory: 1.5Gi

  # Redis Configuration for Sessions and Caching
  # redis:
  #   enabled: true
  #   host: redis-cluster.cache.svc.cluster.local
  #   port: 6379

# Persistent Volumes Configuration with Longhorn
persistence:
  enabled: true
  storageClassName: longhorn-raid-ssd-cached-3-replicas
  accessModes: ReadWriteMany
  size: 2Gi
  keepOnUninstall: false

externalPVC:
  # This will disable the internal storage creation and use the external one defined here
  enabled: false
  # # The external PVC must be created manually before installing the chart
  # # The external PVC must be in the same namespace as the deployment
  # pvcName: clone3-t5-pvc

database:
  namespace: databases
  clusterName: mysql-cluster
  primaryHost: moco-mysql-cluster-primary.databases.svc.cluster.local
  # replicaHost: moco-mysql-cluster-replica.databases.svc.cluster.local # Not working! Needs to be added manually on local.php
  port: 3306
  # table_prefix: mt_ # Not working! Needs to be added using the installer
  dbName: mautic_t5_db
  username: mautic_t5_user
  secretPasswordKey: RFJpUFNWdTVXSFdpYVdoTQ== # base64 format
  # actual password: DRiPSVu5WHWiaWhM