global:
  enableReadinessAndLivenessProbe: true # BUG: Is not working
  preferNodeR913thenR912: false
  preferToDistributePods: true
  preferToRunOnAMD64: true
  domain:
    names: 
      - t5.markitectos.com

# Traefik IngressRoute Configuration
traefik:
  ingressRoute:
    enabled: true

SSLCert:
  enabled: true
  productionReady: false  # on false will use letsencrypt-staging
  keepOnUninstall: false


mautic:
  # Mautic container configurations
  image:
    repository: mautic/mautic
    tag: 5.2.0-apache
    pullPolicy: IfNotPresent

  # Different deployment types
  web:
    replicaCount: 1
    autoscaling:
      enabled: false
      minReplicas: 2
      maxReplicas: 6
      targetCPUUtilization: 70
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1
        memory: 2Gi

  cron:
    replicaCount: 1
    autoscaling:
      enabled: false
      minReplicas: 2
      maxReplicas: 6
      targetCPUUtilization: 70
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

  worker:
    replicaCount: 1
    autoscaling:
      enabled: false
      minReplicas: 2
      maxReplicas: 6
      targetCPUUtilization: 70
    resources:
      requests:
        cpu: 300m
        memory: 756Mi
      limits:
        cpu: 750m
        memory: 1.5Gi

  # Redis Configuration for Sessions and Caching
  # redis:
  #   enabled: true
  #   host: redis-cluster.cache.svc.cluster.local
  #   port: 6379

cronjobs:
  # UPDATE LEAD LISTS (EVERY 15 MINUTES)
  - command: "php /var/www/html/bin/console mautic:segments:update 2>&1"
    schedule: "0,15,30,45 * * * *"
  # UPDATE CAMPAIGNS (EVERY 15 MINUTES)
  - command: "php /var/www/html/bin/console mautic:campaigns:update 2>&1"
    schedule: "5,20,35,50 * * * *"
  # EXECUTE CAMPAIGNS ACTIONS (EVERY 15 MINUTES)
  - command: "php /var/www/html/bin/console mautic:campaigns:trigger 2>&1"
    schedule: "10,25,40,55 * * * *"
  # SEND BROADCAST EMAILS (EVERY 20 MINUTES)
  - command: "php /var/www/html/bin/console mautic:broadcasts:send --limit=10000 2>&1"
    schedule: "0,20,40 * * * *"
  # SEND QUEUE EMAILS (EVERY MINUTE)
  - command: "php /var/www/html/bin/console messenger:consume email --limit=300 2>&1"
    schedule: "* * * * *"
  # UPDATE MAXMIND GEOLITE2 IP DATABASE (Weekly on Sunday at 00:00)
  - command: "php /var/www/html/bin/console mautic:iplookup:download 2>&1"
    schedule: "0 0 * * 0"                

# Persistent Volumes Configuration with Longhorn
persistence:
  enabled: true
  storageClassName: longhorn-raid-ssd-cached-3-replicas
  accessModes: ReadWriteMany
  size: 2Gi
  keepOnUninstall: false

externalPVC:
  # This will disable the internal storage creation and use the external one defined here
  enabled: false
  # # The external PVC must be created manually before installing the chart
  # # The external PVC must be in the same namespace as the deployment
  # pvcName: clone3-t5-pvc

database:
  namespace: databases
  clusterName: mysql-cluster
  primaryHost: moco-mysql-cluster-primary.databases.svc.cluster.local
  # replicaHost: moco-mysql-cluster-replica.databases.svc.cluster.local # Not working! Needs to be added manually on local.php
  port: 3306
  # table_prefix: mt_ # Not working! Needs to be added using the installer
  dbName: mautic_t5_db
  username: mautic_t5_user
  secretPasswordKey: QTVFNkhISUJSV2VZSEFpOA== # base64 format
  # actual password: A5E6HHIBRWeYHAi8