apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-nvme-2-replicas
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "120"
  fromBackup: ""
  diskSelector: "nvme"
  dataLocality: "best-effort"  