apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-raid-ssd-cached-3-replicas
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "120"
  fromBackup: ""
  diskSelector: "raid-ssd-cached"
  dataLocality: "best-effort"  