{{- if and .Values.global .Values.servers }}
{{- range .Values.servers }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $.Values.global.uniqueName }}-{{ .uniqueName }}-certificate
  namespace: {{ $.Values.global.namespace.name }}
spec:
  secretName: {{ $.Values.global.uniqueName }}-{{ .uniqueName }}-ssl-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - '{{ .domain }}'
    - 'www.{{ .domain }}'
{{- end }}
{{- end }}