{{- if and .Values.global .Values.servers }}
{{- range .Values.servers }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $.Values.global.uniqueName }}-{{ .uniqueName }}-ingress-route
  namespace: {{ $.Values.global.namespace.name }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .domain }}`) || Host(`www.{{ .domain }}`)
      kind: Rule
      services:
        - name: {{ $.Values.global.uniqueName }}-nginx
          port: 80
          sticky:
            cookie:
              httpOnly: true
              name: {{ $.Values.global.uniqueName }}-{{ .uniqueName }}-sticky-cookie
              secure: true
              sameSite: none
          strategy: RoundRobin
      middlewares:
        - name: {{ $.Values.global.uniqueName }}-{{ .uniqueName }}-default-headers
  tls:
    secretName: {{ $.Values.global.uniqueName }}-{{ .uniqueName }}-ssl-secret
{{- end }}
{{- end }}
