{{- if .Values.servers }}
{{- range .Values.servers }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ $.Values.global.uniqueName }}-{{ .uniqueName }}-default-headers
  namespace: {{ $.Values.global.namespace.name }}
spec:
  headers:
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 15552000
    customFrameOptionsValue: SAMEORIGIN
    customRequestHeaders:
      X-Forwarded-Proto: https
{{- end }}
{{- end }}