apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.uniqueName }}-nginx
  namespace: {{ .Values.global.namespace.name }}
spec:
  selector:
    app: {{ .Values.global.uniqueName }}-nginx-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80