{{- range .Values.domains.from }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $.Release.Name }}-ingress-route-{{ . | replace "." "-" }}
  namespace: {{ $.Release.Namespace }}
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - match: {{ if $.Values.fromConfigs.addWWW }}Host(`{{ . }}`) || Host(`www.{{ . }}`){{ else }}Host(`{{ . }}`){{ end }}
      kind: Rule
      services:
        - name: {{ $.Release.Name }}-dummy-for-traefik-redirector
          port: 80
      middlewares:
        - name: {{ . | replace "." "-" }}-redirector
  tls:
    secretName: {{ . | replace "." "-" }}-{{ if $.Values.SSLcertificate.productionReady }}prod{{ else }}staging{{ end }}-ssl-secret
{{- end }}