{{- range $.Values.domains.from }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ . | replace "." "-" }}-redirector
  namespace: {{ $.Release.Namespace }}
spec:
  redirectRegex:
    # regex: ^https?://{{ if $.Values.fromConfigs.addWWW }}(www\.)?{{ end }}{{ . }}(.*)
    regex: http(s)?:\/\/(www\.)?{{ . | replace "." "\\." }}\/(.*)
    replacement: https://{{ $.Values.domains.to }}/$3
    permanent: {{ $.Values.fromConfigs.permanent }}
{{- end }}