# IMPORTANT NOTE
# Run the next commands to patch the daemonset after every upgrade:
# k get daemonsets -n longhorn-system
# kubectl patch daemonset <ENGINE IMAGE DAEMONSET NAME> -n longhorn-system -p '{"spec":{"template":{"spec":{"nodeSelector":{"custom.longhorn.instance": "enabled"}}}}}'
# kubectl patch daemonset longhorn-csi-plugin -n longhorn-system -p '{"spec":{"template":{"spec":{"nodeSelector":{"custom.longhorn.instance": "enabled"}}}}}'

global:
  nodeSelector:
    custom.longhorn.instance: "enabled"  
  cattle:
    defaultSetting:
      taintToleration: custom.longhorn.instance=enabled:NoSchedule
      systemManagedComponentsNodeSelector: custom.longhorn.instance:enabled 

defaultSettings:
  # -- Taint or toleration for system-managed Longhorn components.
  # Specify values using a semicolon-separated list in `kubectl taint` syntax (Example: key1=value1:effect; key2=value2:effect).
  taintToleration: custom.longhorn.instance=enabled:NoSchedule
  # -- Node selector for system-managed Longhorn components.
  systemManagedComponentsNodeSelector: custom.longhorn.instance:enabled
  # -- Percentage of the total allocatable CPU resources on each node to be reserved for each instance manager pod when the V1 Data Engine is enabled. The default value is "12".
  guaranteedInstanceManagerCPU: 4

longhornManager:
  nodeSelector:
    custom.longhorn.instance: "enabled"
  # tolerations:
  #   - effect: NoSchedule
  #     operator: Exists
longhornDriver:
  nodeSelector:
    custom.longhorn.instance: "enabled"
  # tolerations:
  #   - effect: NoSchedule
  #     operator: Exists
longhornUI:
  replicas: 2
  nodeSelector:
    custom.longhorn.instance: "enabled"
  # tolerations:
  #   - effect: NoSchedule
  #     operator: Exists