services:
  wordpress:
    image: markitectos/testing:custom_wp6.6.1-php8.3-fpm-alpine
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
    depends_on:
      - db

  db:
    image: percona/percona-server:8.0.37-29
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    command: >
      --default-authentication-plugin=mysql_native_password
      --tls-version=TLSv1.2,TLSv1.3
    deploy:
      resources:
        limits:
          memory: 512M


