services:
  wordpress:
    image: markitectos/production:custom_wp6.6.2-php8.3-fpm-alpine-v3
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      PHP_INI_SCAN_DIR: :/usr/local/etc/php/conf.d/custom-conf
    depends_on:
      - db
    volumes:
      - ./custom-php.ini:/usr/local/etc/php/conf.d/custom-conf/custom-php.ini

  db:
    image: percona/percona-server:8.0.37-29
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    privileged: true
    command: >
      --tls-version=TLSv1.2,TLSv1.3
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_520_ci
    deploy:
      resources:
        limits:
          memory: 512M


