services:
  wordpress:
    image: test_custom_wp6.6.2-php8.3-fpm-alpine
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
    depends_on:
      - db
    volumes:
      - ./db-config.php:/var/www/html/db-config.php
    #   - ./custom-wp-config.php:/var/www/html/wp-config.php

  db:
    image: percona/percona-server:8.0.37-29
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    privileged: true
    command: >
      --tls-version=TLSv1.2,TLSv1.3
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_520_ci
    deploy:
      resources:
        limits:
          memory: 512M


