## https://www.youtube.com/watch?v=n5dpQLqOfqM
## https://github.com/ChristianLempa/boilerplates

# apiVersion: v1
# kind: Namespace
# metadata:
#   name: whoami
#   labels:
#     name: whoami

# ---

apiVersion: v1
kind: ConfigMap
metadata:
  name: whoami-custom-php-ini
  namespace: percona
data:
  custom-php.ini: |+
    upload_max_filesize = 100M
    post_max_size = 100M
    memory_limit = 256M
    max_execution_time = 600
    max_input_vars = 1000
    max_input_time = 400

    extension=redis.so
    ;session.save_handler = rediscluster
    ;session.save_path = "tcp://redis-node-0.redis-headless.redis.svc.cluster.local:26379,tcp://redis-node-1.redis-headless.redis.svc.cluster.local:26379,tcp://redis-node-2.redis-headless.redis.svc.cluster.local:26379"
    session.save_handler = files 
    session.save_path = /var/www/html/wp-content/sessions

---

# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: whoami-custom-apache-config
#   namespace: percona
# data:
#   000-default.conf: |+
#     <VirtualHost *:80>
#         ServerName whoami.markitectos.com
#         DocumentRoot /var/www/html
#         <Directory /var/www/html>
#             AllowOverride All
#             Require all granted
#         </Directory>
#     </VirtualHost>

# ---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whoami-pvc
  namespace: percona
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi

---     


# Wordpress Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: percona
spec:
  selector:
    matchLabels:
      app: whoami-app
  replicas: 1
  template:
    metadata:
      labels:
        app: whoami-app
        redis-client: "true"
    spec:
###############################################################
      initContainers:
        - name: install-redis-extension
          image: wordpress:6.5.5-php8.3-apache
          command:
            - sh
            - -c
            - |
              apt-get update && \
              apt-get install -y libcurl4-openssl-dev pkg-config libssl-dev zlib1g-dev && \
              printf "\n" | pecl install redis && \
              mkdir -p /php-extensions && \
              cp /usr/local/lib/php/extensions/no-debug-non-zts-20230831/redis.so /php-extensions/
          volumeMounts:
            - mountPath: /php-extensions
              name: php-extensions
################################################################    
      volumes:
        - name: whoami-pv
          persistentVolumeClaim:
            claimName: whoami-pvc      
################################################################  
        - name: php-extensions
          emptyDir: {}
################################################################  
        - name: whoami-custom-php-ini
          configMap:
            name: whoami-custom-php-ini
        # - name: whoami-custom-apache-config
        #   configMap:
        #     name: whoami-custom-apache-config            
      # nodeSelector:
      #   kubernetes.io/hostname: r7-11
      hostAliases:
      - ip: 168.205.123.10
        hostnames:
        - whoami.markitectos.com
      # - ip: 127.0.0.1
      #   hostnames:
      #   - whoami.markitectos.com        
      containers:
        - name: whoami-container
          image: 'wordpress:6.5.5-php8.3-apache' # wordpress:6.4.1-php8.2-apache
          volumeMounts:
            - mountPath: "/var/www/html/wp-content"
              name: whoami-pv        
              ################################################################    
            - mountPath: /usr/local/lib/php/extensions/no-debug-non-zts-20230831/redis.so
              subPath: redis.so
              name: php-extensions
              readOnly: true
              ################################################################    
            - mountPath: /usr/local/etc/php/conf.d/custom-conf
              name: whoami-custom-php-ini
              readOnly: true
            # - mountPath: /etc/apache2/sites-available
            #   name: whoami-custom-apache-config
            #   readOnly: true              
            # - mountPath: "/other/path"
            #   name: other-pv-storage
            # - mountPath: "/other/path"
            #   name: other-pv-storage                     
          # resources:
          #   requests:
          #     memory: "256Mi" # Memory reserved
          #     cpu: "500m" # CPU reserved
          #   limits:
          #      memory: "512Mi" # Maximum memory allowed
          #      cpu: "1000m" # Maximum CPU allowed
          env:
            - name: WORDPRESS_DB_HOST
              value: percona-db-pxc-db-haproxy-replicas.percona.svc.cluster.local:3306 # DIRECT TO NODES: whoami-data-pxc-db-pxc-0.whoami-data-pxc-db-pxc.whoami.svc.cluster.local:3306,whoami-data-pxc-db-pxc-1.whoami-data-pxc-db-pxc.whoami.svc.cluster.local:3306,whoami-data-pxc-db-pxc-2.whoami-data-pxc-db-pxc.whoami.svc.cluster.local:3306
            - name: WORDPRESS_DB_NAME # needs to already exist on the given MySQL server; it will not be created by the wordpress container
              value: whoami_markitectos
            - name: WORDPRESS_DB_USER
              value: whoami_markitectos_user
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: whoami-whoami-pass
                  key: password
            - name: WORDPRESS_TABLE_PREFIX
              value: wp_
            - name: WORDPRESS_DEBUG # defaults to disabled, non-empty value will enable WP_DEBUG in wp-config.php
              value: 'true'
            - name: PHP_INI_SCAN_DIR
              value: :/usr/local/etc/php/conf.d/custom-conf
            - name: WORDPRESS_CONFIG_EXTRA
              value: |
                define( 'WP_HOME', 'https://' . $_SERVER['HTTP_HOST'] . '/' );
                define( 'WP_SITEURL', 'https://' . $_SERVER['HTTP_HOST'] . '/' );
                define( 'WP_AUTO_UPDATE_CORE', false );
                define('WP_DEBUG', true);
                define('WP_DEBUG_LOG', true);
                define( 'WP_DEBUG_DISPLAY', true );
                /// define( 'WP_CACHE', true );
                // change the prefix and database for each site to avoid cache data collisions
                /// define( 'WP_REDIS_SENTINEL', 'mymaster' );
                /// define( 'WP_REDIS_DATABASE', 0 );
                /// define( 'WP_REDIS_PREFIX', 'whoami_markitectos_com' );
 
                // @ini_set('session.save_handler', 'files');
                // @ini_set('session.save_path', '/var/www/html/wp-content';

                // Redis session configuration
                /// define( 'WP_REDIS_SESSION_HANDLER', true );
                /// define( 'WP_REDIS_SESSION_TTL', 3600 );

                // Enable Redis for PHP sessions
                // @ini_set('session.save_handler', 'redis');
                // @ini_set('session.save_path', 'tcp://redis-node-0.redis-headless.redis.svc.cluster.local:26379,tcp://redis-node-1.redis-headless.redis.svc.cluster.local:26379,tcp://redis-node-2.redis-headless.redis.svc.cluster.local:26379?sentinel=mymaster');
                //////////////////////////////////////////////////////////////////
                // define('WP_SESSION_SAVE_PATH', 'tcp://redis-node-0.redis-headless.redis.svc.cluster.local:26379,tcp://redis-node-1.redis-headless.redis.svc.cluster.local:26379,tcp://redis-node-2.redis-headless.redis.svc.cluster.local:26379?sentinel=mymaster');
                //////////////////////////////////////////////////////////////////
                // redis access data
                // define( 'WP_REDIS_PASSWORD', 'wOaxfmztJT' );
                // define( 'WP_REDIS_SENTINEL_PASSWORD', 'wOaxfmztJT' );
                // define( 'WP_REDIS_PASSWORD', [ 'default', 'wOaxfmztJT' ] );

                // Enable Redis debug logging
                /// define( 'WP_REDIS_DISABLED', false );
                /// define( 'WP_REDIS_GRACEFUL', true );
                /// define( 'WP_REDIS_IGBINARY', false );
                /// define( 'WP_REDIS_MAXTTL', 3600 );
                /// define( 'WP_REDIS_CLIENT', 'predis' );             

                // reasonable connection and read+write timeouts
                /// define( 'WP_REDIS_TIMEOUT', 1 );
                /// define( 'WP_REDIS_READ_TIMEOUT', 1 );
                // set redis sentinel servers
                /// define( 'WP_REDIS_SERVERS', [
                ///   'tcp://redis-node-0.redis-headless.redis.svc.cluster.local:26379',
                ///   'tcp://redis-node-1.redis-headless.redis.svc.cluster.local:26379',
                ///   'tcp://redis-node-2.redis-headless.redis.svc.cluster.local:26379'
                /// ]);           


                // Error logging

                @ini_set( 'log_errors', 'On' );
                @ini_set( 'display_errors', 'On' );
                @ini_set( 'error_log', '/var/www/html/wp-content/debug.log' );
                $_SERVER['HTTPS']='on';
          ports:
            - containerPort: 80 
          imagePullPolicy: Always # IfNotPresent or Always
          livenessProbe: # Check if pod is alive, if not restart
            failureThreshold: 6
            httpGet:
              path: /wp-admin/install.php
              port: 80
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          ##
          ## TODO: We will have to figure out how to add a readiness probe that runs with this image that starts without install
          ##
          readinessProbe: # Check if pod is ready, and enable it to get traffic only when is ready
           failureThreshold: 6
           httpGet:
             path: /wp-login.php
             port: 80
             scheme: HTTP
           initialDelaySeconds: 30
           periodSeconds: 30
           successThreshold: 1
           timeoutSeconds: 5
          lifecycle:
            postStart:
              exec:
                command: 
                  - "/bin/sh"
                  - "-c"
                  - >
                    mkdir -p /var/www/html/wp-content/sessions &&
                    chown www-data:www-data /var/www/html/wp-content/sessions &&
                    chmod 755 /var/www/html/wp-content/sessions &&
                    rm -r /var/www/html/wp-content/themes/twentytwentytwo &&
                    rm -r /var/www/html/wp-content/themes/twentytwentythree &&
                    rm -r /var/www/html/wp-content/plugins/akismet &&
                    rm /var/www/html/wp-content/plugins/hello.php
---


## To create the password value in base 64 to set this secret
# echo -n '<your_password>' | base64

## Sets the Secret Password for whoami DB
apiVersion: v1
kind: Secret
metadata:
  name: whoami-whoami-pass
  namespace: percona  
type: Opaque
data:
  password: TWF4aTE0NjUh


---

## https://github.com/dmancloud/traefik-cert-manager/blob/main/nginx/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: whoami-service
  namespace: percona
spec:
  type: ClusterIP
  selector:
    app: whoami-app
  ports:
    - name: http
      port: 80
      targetPort: 80

---

## https://github.com/dmancloud/traefik-cert-manager/blob/main/traefik/default-headers.yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: default-headers
  namespace: percona
spec:
  headers:
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 15552000
    customFrameOptionsValue: SAMEORIGIN
    customRequestHeaders:
      X-Forwarded-Proto: https

---
## https://github.com/dmancloud/traefik-cert-manager/blob/main/nginx/ingress.yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-ingress-route
  namespace: percona
  annotations: 
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`www.whoami.markitectos.com`) || Host(`whoami.markitectos.com`)
      kind: Rule
      services:
        - name: whoami-service
          port: 80
      middlewares:
        - name: default-headers
  tls:
    secretName: whoami-markitectos-ssl-secret


---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whoami-markitectos-certificate
  namespace: percona
spec:
  secretName: whoami-markitectos-ssl-secret
  issuerRef:
    # name: letsencrypt-staging
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - 'whoami.markitectos.com'
    - 'www.whoami.markitectos.com'