apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: databases
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        env:
        - name: PMA_HOST
          value: "moco-mysql-cluster-primary.databases.svc.cluster.local"
        - name: PMA_PORT
          value: "3306"  # Default MySQL port
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  namespace: databases
spec:
  selector:
    app: phpmyadmin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP  # Use "ClusterIP" for internal access only, or "LoadBalancer" for external access if supported

---

apiVersion: ui.cattle.io/v1
kind: NavLink
metadata:
  name: phpmyadmin
spec:
  label: phpMyAdmin
  target: _blank
  toService:
    name: phpmyadmin-service
    namespace: databases
    path: /
    port: '80'
    scheme: http


