## To create the password value in base 64 to set this secret
# echo -n '<your_password>' | base64

## Sets the Secret Password for the DB
{{- if eq .Values.database.mode "bitpoke" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-bitpoke-db-pass
  namespace: {{ .Values.database.bitpoke.namespace }}
  annotations:
    {{- if $.Values.database.bitpoke.keepOnUninstall }}
    helm.sh/resource-policy: keep
    {{- end }}
type: Opaque
data:
  password: {{ .Values.database.bitpoke.secretPasswordKey }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-bitpoke-db-pass
  namespace: {{ $.Release.Namespace }}
  annotations:
    {{- if $.Values.database.bitpoke.keepOnUninstall }}
    helm.sh/resource-policy: keep
    {{- end }}
type: Opaque
data:
  password: {{ .Values.database.bitpoke.secretPasswordKey }}
{{- end }}    