{{- if eq .Values.database.mode "bitpoke" }}
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlUser
metadata:
  name: {{ $.Release.Name }}-user
  namespace: {{ .Values.database.bitpoke.namespace }}
  annotations:
    {{- if $.Values.database.bitpoke.keepOnUninstall }}
    helm.sh/resource-policy: keep
    {{- end }}
spec:
  user: {{ $.Release.Name }}-username
  clusterRef:
    name: {{ .Values.database.bitpoke.clusterName }}
    namespace: {{ .Values.database.bitpoke.namespace }}
  password:
    name: {{ $.Release.Name }}-bitpoke-db-pass
    key: password    
  allowedHosts:
    - "%"
  permissions:
    - schema: {{ $.Release.Name }}-db-name
      tables: ["*"]
      permissions:
        - ALL PRIVILEGES
{{- end }}        