{{- if $.Values.bitpokeDB.enabled }}
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlUser
metadata:
  name: {{ .Values.global.uniqueName }}-user
  namespace: {{ .Values.bitpokeDB.namespace }}
  annotations:
    {{- if $.Values.bitpokeDB.keepOnUninstall }}
    helm.sh/resource-policy: keep
    {{- end }}
spec:
  user: {{ .Values.global.uniqueName }}-username
  clusterRef:
    name: {{ .Values.bitpokeDB.clusterName }}
    namespace: {{ .Values.bitpokeDB.namespace }}
  password:
    name: {{ .Values.global.uniqueName }}-bitpoke-db-pass
    key: password    
  allowedHosts:
    - "%"
  permissions:
    - schema: {{ .Values.global.uniqueName }}-db-name
      tables: ["*"]
      permissions:
        - ALL PRIVILEGES
{{- end }}        