{{- if eq .Values.database.mode "bitpoke" }}
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlDatabase
metadata:
  name: {{ $.Release.Name }}-database
  namespace: {{ .Values.database.bitpoke.namespace }}  
  annotations:
    {{- if $.Values.database.bitpoke.keepOnUninstall }}
    helm.sh/resource-policy: keep
    {{- end }}
spec:
  database: {{ $.Release.Name }}-db-name
  clusterRef:
    name: {{ .Values.database.bitpoke.clusterName }}
    namespace: {{ .Values.database.bitpoke.namespace }}
{{- end }}     