{{- if $.Values.bitpokeDB.enabled }}
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlDatabase
metadata:
  name: {{ $.Release.Name }}-database
  namespace: {{ .Values.bitpokeDB.namespace }}  
  annotations:
    {{- if $.Values.bitpokeDB.keepOnUninstall }}
    helm.sh/resource-policy: keep
    {{- end }}
spec:
  database: {{ $.Release.Name }}-db-name
  clusterRef:
    name: {{ .Values.bitpokeDB.clusterName }}
    namespace: {{ .Values.bitpokeDB.namespace }}
{{- end }}     