apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $.Values.global.uniqueName }}-certificate
  namespace: {{ $.Values.global.namespace.name }}
  annotations:
    {{- if $.Values.SSLcertificate.keepOnUninstall }}
    helm.sh/resource-policy: keep
    {{- end }}
spec:
  secretName: {{ $.Values.global.uniqueName }}-ssl-secret
  issuerRef:
    {{- if .Values.SSLcertificate.productionReady }}
    name: letsencrypt-production
    {{- else }}
    name: letsencrypt-staging
    {{- end }}
    kind: ClusterIssuer
  dnsNames:
    {{- range $.Values.domains }}
    - '{{ .name }}'
    - 'www.{{ .name }}'
    {{- end }}