apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-db-cluster-config
  namespace: {{ $.Release.Namespace }}
data:
  db-config.php: |
    <?php

    /*
    * LudicrousDB configuration file
    *
    * This file should be copied to ABSPATH/db-config.php and modified to suit your
    * database environment. This file comes with a basic configuration by default.
    *
    * See README.md for documentation.
    */

    // Exit if accessed directly
    defined( 'ABSPATH' ) || exit;

    /**
    * This sets the default character set. Since WordPress 4.2, the suggested
    * setting is "utf8mb4". We strongly recommend not downgrading to utf8,
    * using latin1, or sticking to the default: utf8mb4.
    *
    * Default: utf8mb4
    */
    $wpdb->charset = 'utf8mb4';

    /**
    * This sets the default column collation. For best results, investigate which
    * collation is recommended for your specific character set.
    *
    * Default: utf8mb4_unicode_520_ci
    */
    $wpdb->collate = 'utf8mb4_unicode_520_ci';

    /**
    * This is useful for debugging. Queries are saved in $wpdb->queries. It is not
    * a constant because you might want to use it momentarily.
    * Default: false
    */
    $wpdb->save_queries = false;

    /**
    * The amount of time to wait before trying again to ping mysql server.
    *
    * Default: 0.1 (Seconds)
    */
    $wpdb->recheck_timeout = 0.1;

    /**
    * This determines whether to use mysql_connect or mysql_pconnect. The effects
    * of this setting may vary and should be carefully tested.
    *
    * Default: false
    */
    $wpdb->persistent = false;

    /**
    * This determines whether to use mysql connect or mysql connect has failed and to bail loading the rest of WordPress
    *
    * Default: false
    */
    $wpdb->allow_bail = false;

    /**
    * This is the number of mysql connections to keep open. Increase if you expect
    * to reuse a lot of connections to different servers. This is ignored if you
    * enable persistent connections.
    *
    * Default: 10
    */
    $wpdb->max_connections = 100;

    /**
    * Enables checking TCP responsiveness by fsockopen prior to mysql_connect or
    * mysql_pconnect. This was added because PHP's mysql functions do not provide
    * a variable timeout setting. Disabling it may improve average performance by
    * a very tiny margin but lose protection against connections failing slowly.
    *
    * Default: true
    */
    $wpdb->check_tcp_responsiveness = true;

    /**
    * The cache group that is used to store TCP responsiveness.
    *
    * Default: ludicrousdb
    */
    $wpdb->cache_group = 'ludicrousdb';

    /**
    * This is the most basic way to add a server to LudicrousDB using only the
    * required parameters: host, user, password, name.
    * This adds the DB defined in wp-config.php as a read/write server for
    * the 'global' dataset. (Every table is in 'global' by default.)
    */
    // $wpdb->add_database(
    // 	array(
    // 		'host'     => DB_HOST,     // If port is other than 3306, use host:port.
    // 		'user'     => DB_USER,
    // 		'password' => DB_PASSWORD,
    // 		'name'     => DB_NAME,
    // 	)
    // );

    /**
    * This adds the same server again, only this time it is configured as a replica.
    * The last three parameters are set to the defaults but are shown for clarity.
    */
    // $wpdb->add_database(
    // 	array(
    // 		'host'     => DB_HOST,     // If port is other than 3306, use host:port.
    // 		'user'     => DB_USER,
    // 		'password' => DB_PASSWORD,
    // 		'name'     => DB_NAME,
    // 		'write'    => 0,
    // 		'read'     => 1,
    // 		'dataset'  => 'global',
    // 		'timeout'  => 0.2,
    // 	)
    // );


    // This primary DB is the Master and works when bitpoke is enabled or disabled
    $wpdb->add_database(array(
        'host'     => getenv('WORDPRESS_DB_HOST'), // If port is other than 3306, use host:port.
        'user'     => getenv('WORDPRESS_DB_USER'),
        'password' => getenv('WORDPRESS_DB_PASSWORD'),
        'name'     => getenv('WORDPRESS_DB_NAME'),
        'write'    => 1,
        // Reads are limited to the primary DB when bitpoke is enabled
        {{- if $.Values.bitpokeDB.enabled }}
        'read'     => 10,
        {{- end }}
        {{- if not $.Values.bitpokeDB.enabled }}
        'read'     => 1,        
        {{- end }}
        'dataset'  => 'global',
        'timeout'  => 0.2,
    ));
    // This replica DB is used only when bitpoke is enabled
    {{- if $.Values.bitpokeDB.enabled }}
    $wpdb->add_database(array(
        'host'     => '{{ .Values.bitpokeDB.clusterName }}-mysql-replicas.{{ .Values.bitpokeDB.namespace }}.svc.cluster.local:3306',
        'user'     => getenv('WORDPRESS_DB_USER'),
        'password' => getenv('WORDPRESS_DB_PASSWORD'),
        'name'     => getenv('WORDPRESS_DB_NAME'),
        'write'    => 0,
        'read'     => 1,
        'dataset'  => 'global',
        'timeout'  => 0.2,
    ));
    {{- end }}