## To create the password value in base 64 to set this secret
# echo -n '<your_password>' | base64

## Sets the Secret Password for the DB
{{- if eq .Values.database.mode "default" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-default-db-pass
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  password: {{ .Values.database.default.SecretPasswordKey }}
{{- end }}   