apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.global.namespace.name }}
  name: {{ .Values.global.uniqueName }}-nginx-wordpress
spec:
  {{- if not $.Values.global.autoscaling.enabled }}
  replicas: {{ .Values.global.replicas }}
  {{- end }}
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Values.global.uniqueName }}-nginx-wordpress
  template:
    metadata:
      labels:
        app: {{ .Values.global.uniqueName }}-nginx-wordpress
    spec:
      affinity:
        {{- if $.Values.global.preferToRunOnAMD64 }}
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 90
              preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
        {{- end }}
        {{- if $.Values.global.preferToDistributePods }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ .Values.global.uniqueName }}-nginx-wordpress
                topologyKey: "kubernetes.io/hostname"
        {{- end }}
      volumes:
        {{- if $.Values.wordpress.customPHPini.enabled }}
        - name: {{ .Values.global.uniqueName }}-wp-custom-php-ini
          configMap:
            name: {{ .Values.global.uniqueName }}-wp-custom-php-ini
        {{- end }}
        {{- if .Values.wordpress.storage.enabled }}
        - name: {{ .Values.global.uniqueName }}-wp-content-pv
          persistentVolumeClaim:
            claimName: {{ .Values.global.uniqueName }}-wp-content-pvc
        {{- end }}
        {{- if $.Values.bitpokeDB.enabled }}
        - name: db-cluster-config
          configMap:
            name: {{ .Values.global.uniqueName }}-db-cluster-config
        {{- end }}
      {{- if $.Values.bitpokeDB.enabled }}
      initContainers:
        - name: init-db-cluster-config
          image: busybox
          command: ['sh', '-c', 'cp /tmp/db-cluster-config/db-cluster-config.php /var/www/html/wp-content/db-cluster-config.php && chown 82:82 /var/www/html/wp-content/db-cluster-config.php']
          volumeMounts:
            - name: db-cluster-config
              mountPath: /tmp/db-cluster-config
            - name: {{ .Values.global.uniqueName }}-wp-content-pv
              mountPath: /var/www/html/wp-content
      {{- end }}
      containers:
        - name: nginx-wordpress
          image: {{ .Values.global.deploymentCustomImage }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: 80
            - containerPort: 9000
          volumeMounts:
            {{- if $.Values.wordpress.customPHPini.enabled }}
            - name: {{ .Values.global.uniqueName }}-wp-custom-php-ini
              mountPath: /usr/local/etc/php/conf.d/custom-conf
              readOnly: true
            {{- end }}
            {{- if .Values.wordpress.storage.enabled }}
            - name: {{ .Values.global.uniqueName }}-wp-content-pv
              mountPath: /var/www/html/wp-content
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ .Values.global.uniqueName }}-wordpress-configmap
          env:
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if $.Values.bitpokeDB.enabled }}
                  name: {{ .Values.global.uniqueName }}-bitpoke-db-pass
                  key: password
                  {{- end }}
                  {{- if not $.Values.bitpokeDB.enabled }}
                  name: {{ .Values.global.uniqueName }}-db-pass
                  key: password
                  {{- end }}
          resources:
            {{- if .Values.resources.enableLimits }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            {{- end }}
            {{- if .Values.resources.enableRequests }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            {{- end }}
  
