{{- if $.Values.global.autoscaling.enabled }}
{{- if $.Values.resources.enableRequests }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $.Release.Name }}-hpa
  namespace: {{ $.Release.Namespace }}  
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $.Release.Name }}-nginx-wordpress
  minReplicas: {{ $.Values.global.autoscaling.minReplicas }}
  maxReplicas: {{ $.Values.global.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ $.Values.global.autoscaling.targetCPUUtilization }}
{{- end }}
{{- end }}