apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $.Values.global.uniqueName }}-ingress-route
  namespace: {{ $.Values.global.namespace.name }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: {{ range $index, $domain := $.Values.domains }}{{ if $index }} || {{ end }}Host(`{{ $domain.name }}`){{ end }}
      kind: Rule
      services:
        - name: {{ .Values.global.uniqueName }}-nginx-wordpress
          port: 80
          sticky:
            cookie:
              httpOnly: true
              name: {{ $.Values.global.uniqueName }}-sticky-cookie
              secure: true
              sameSite: none
          strategy: RoundRobin
      middlewares:
        - name: {{ $.Values.global.uniqueName }}-default-headers
    - match: {{ range $index, $domain := $.Values.domains }}{{ if $index }} || {{ end }}Host(`www.{{ $domain.name }}`){{ end }}
      kind: Rule
      middlewares:
        - name: {{ $.Values.global.uniqueName }}-www-redirect
  tls:
    secretName: {{ $.Values.global.uniqueName }}-ssl-secret
