{{- range .Values.domains.names }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $.Release.Name }}-ingress-route-{{ . | replace "." "-" }}
  namespace: {{ $.Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ . }}`)
      kind: Rule
      services:
        - name: {{ $.Release.Name }}-nginx-wordpress
          port: 80
          sticky:
            cookie:
              httpOnly: true
              name: {{ . | replace "." "-" }}-sticky-cookie
              secure: true
              sameSite: none
          strategy: RoundRobin
      middlewares:
        - name: {{ . | replace "." "-" }}-default-headers
  tls:
    secretName: {{ . | replace "." "-" }}-{{ if $.Values.SSLcertificate.productionReady }}prod{{ else }}staging{{ end }}-ssl-secret

{{- if $.Values.domains.addWWW }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $.Release.Name }}-ingress-route-www-{{ . | replace "." "-" }}
  namespace: {{ $.Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`www.{{ . }}`)
      kind: Rule
      services:
        - name: {{ $.Release.Name }}-nginx-wordpress
          port: 80
          sticky:
            cookie:
              httpOnly: true
              name: {{ . | replace "." "-" }}-sticky-cookie
              secure: true
              sameSite: none
          strategy: RoundRobin
      middlewares:
        - name: {{ . | replace "." "-" }}-www-redirect
  tls:
    secretName: {{ . | replace "." "-" }}-{{ if $.Values.SSLcertificate.productionReady }}prod{{ else }}staging{{ end }}-ssl-secret
{{- end }}
{{- end }}