apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $.Release.Name }}-ingress-route
  namespace: {{ $.Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: {{ range $index, $domain := $.Values.domains.names }}{{ if $index }} || {{ end }}Host(`{{ $domain }}`){{ end }}
      kind: Rule
      services:
        - name: {{ $.Release.Name }}-nginx-wordpress
          port: 80
          sticky:
            cookie:
              httpOnly: true
              name: {{ $.Release.Name }}-sticky-cookie
              secure: true
              sameSite: none
          strategy: RoundRobin
      middlewares:
        - name: {{ $.Release.Name }}-default-headers
    {{- if $.Values.domains.addWWW }}
    - match: {{ range $index, $domain := $.Values.domains.names }}{{ if $index }} || {{ end }}Host(`www.{{ $domain }}`){{ end }}
      kind: Rule
      middlewares:
        {{- if $.Values.domains.redirectWWWtoNonWWW }}
        - name: {{ $.Release.Name }}-to-non-www-redirect
        {{- else }}
        - name: {{ $.Release.Name }}-default-headers
      services:
        - name: {{ $.Release.Name }}-nginx-wordpress
          port: 80
          sticky:
            cookie:
              httpOnly: true
              name: {{ $.Release.Name }}-sticky-cookie
              secure: true
              sameSite: none
          strategy: RoundRobin
        {{- end }}
    {{- end }}  
  tls:
    secretName: {{ $.Release.Name }}-ssl-secret