{{- if and .Values.wordpress.storage.enabled .Values.wordpress.storage.backups.enabled }}
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: {{ .Release.Name }}-wp-content-backup
  namespace: longhorn-system
spec:
  cron: {{ .Values.wordpress.storage.backups.schedule | quote }}
  task: "backup"
  groups:
  - {{ .Release.Name }}-wp-content
  retain: {{ .Values.wordpress.storage.backups.retention }}
  concurrency: 1
{{- end }}