{{- if and .Values.wordpress.storage.enabled .Values.wordpress.storage.snapshots.enabled }}
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: {{ .Release.Name }}-wp-content-snapshot
  namespace: longhorn-system
spec:
  cron: {{ .Values.wordpress.storage.snapshots.schedule | quote }}
  task: "snapshot"
  groups:
  - {{ .Release.Name }}-wp-content
  retain: {{ .Values.wordpress.storage.snapshots.retention }}
  concurrency: 2
{{- end }}