apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $.Values.global.uniqueName }}-default-headers
  namespace: {{ $.Values.global.namespace.name }}
spec:
  headers:
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 15552000
    customFrameOptionsValue: SAMEORIGIN
    customRequestHeaders:
      X-Forwarded-Proto: https

---

apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $.Values.global.uniqueName }}-www-redirect
  namespace: {{ $.Values.global.namespace.name }}
spec:
  redirectRegex:
    regex: ^https?://www\.(.*)
    replacement: https://$1
    permanent: true