{{- if $.Values.global.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $.Values.global.namespace.name }}
  annotations:
    {{- if $.Values.global.namespace.keepOnUninstall }}
    helm.sh/resource-policy: keep
    {{- end }}  
  labels:
    name: {{ $.Values.global.namespace.name }}
{{- end }}      