{{- if $.Values.nginx.customNginxConf.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-nginx-conf
  namespace: {{ $.Release.Namespace }}
data:
  nginx.conf: |
    user nginx;

    # Set to number of CPU cores, auto will try to autodetect.
    worker_processes auto;

    # Maximum open file descriptors per process. Should be greater than worker_connections.
    worker_rlimit_nofile 8192;

    # for faster regular expressions
    pcre_jit on;

    # Default Logs
    # access_log /dev/stdout combined;
    error_log /dev/stderr warn;

    # Load the extra modules (including cache purge)
    include /etc/nginx/modules/*.conf;

    events {
      # Set the maximum number of connection each worker process can open. Anything higher than this
      # will require Unix optimisations.
      worker_connections 8000;

      # Accept all new connections as they're opened.
      multi_accept on;

    }

    http {

      ### GENERAL HTTP ###

      # Speed up file transfer by using sendfile().
      sendfile on;

      # Don't send partial frames, which increases throughput.
      tcp_nopush on;

      # Don't wait to send data in keep-alive state.
      tcp_nodelay on;     

      # MIME Types
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;

      ### LIMITS & TIMEOUTS ###

      # How long each connection should stay open for.
      keepalive_timeout 15;

      # Timeout for reading client request body.
      client_body_timeout 30;

      # Timeout for reading client request header.
      client_header_timeout 30;

      # Timeout for transmitting reponse to client.
      send_timeout 30;

      # Set the maximum allowed size of client request body. This should be set
      # to the value of files sizes you wish to upload to the WordPress Media Library.
      # You may also need to change the values `upload_max_filesize` and `post_max_size` within
      # your php.ini for the changes to apply.
      client_max_body_size {{ $.Values.nginx.customNginxConf.clientMaxBodySizeMB }}m;        

      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

      # Some WP plugins that push large amounts of data via cookies
      # can cause 500 HTTP errors if these values aren't increased.
      fastcgi_buffers 16 16k;
      fastcgi_buffer_size 32k;

      ### GZIP CONFIGS ###

      # Enable Gzip compression.
      gzip on;

      # Allow proxies to cache both compressed and regular version of file.
      # Avoids clients that don't support Gzip outputting gibberish.
      gzip_vary on;

      # Compress data, even when the client connects through a proxy.
      gzip_proxied any;

      # The level of compression to apply to files. A higher compression level increases
      # CPU usage. Level 5 is a happy medium resulting in roughly 75% compression.
      gzip_comp_level 5;

      # The minimum HTTP version of a request to perform compression.
      gzip_http_version 1.1;

      # Don't compress files smaller than 256 bytes, as size reduction will be negligible.
      gzip_min_length 256;

      # Compress the following MIME types.
      gzip_types
        application/atom+xml
        application/javascript
        application/json
        application/ld+json
        application/manifest+json
        application/rss+xml
        application/vnd.geo+json
        application/vnd.ms-fontobject
        application/x-font-ttf
        application/x-web-app-manifest+json
        application/xhtml+xml
        application/xml
        font/opentype
        image/bmp
        image/svg+xml
        image/x-icon
        text/cache-manifest
        text/css
        text/plain
        text/vcard
        text/vnd.rim.location.xloc
        text/vtt
        text/x-component
        text/x-cross-domain-policy;
        # text/html is always compressed when enabled.

      # Adds the server files
      include /etc/nginx/http.d/*.conf;

      ## SSL SECURITY

      ssl_protocols TLSv1.2 TLSv1.3;
      ssl_prefer_server_ciphers on;
      ssl_session_cache shared:SSL:2m;
      ssl_session_timeout 2h;
      ssl_session_tickets off;


      ## Control how much referrer information should be included with requests
      add_header Referrer-Policy "no-referrer-when-downgrade" always;

    }
{{- end }}