apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.global.namespace.name }}
  name: {{ .Values.global.uniqueName }}-nginx-wordpress
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: {{ .Values.global.uniqueName }}-nginx-wordpress
  sessionAffinity: None
  type: ClusterIP      