{{- if .Values.wordpress.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.global.uniqueName }}-wp-content-pvc
  namespace: {{ .Values.global.namespace.name }}
spec:
  accessModes:
    - {{ .Values.wordpress.storage.accessModes | quote }}
{{- if .Values.wordpress.storage.class }}
  {{- if (eq "-" .Values.wordpress.storage.class) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.wordpress.storage.class }}
  {{- end }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.wordpress.storage.size | quote }}
{{- end }}      