# apiVersion: v1
# kind: Service
# metadata:
#   name: custom-mariadb-galera-service
#   labels:
#     app: mariadb-galera
# spec:
#   ports:
#     - port: 3306
#       targetPort: 3306
#   selector:
#     app.kubernetes.io/name: mariadb
#   type: ClusterIP

# ---  

apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-galera
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password
  username: mariadb
  passwordSecretKeyRef:
    name: mariadb
    key: password
  database: mariadb

  storage:
    size: 1Gi
    storageClassName: local-path
    resizeInUseVolumes: true
    waitForVolumeResize: true
    volumeClaimTemplate:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: local-path

  replicas: 3

  galera:
    enabled: true

  service:
    type: ClusterIP
  
  connection:
    secretName: mariadb-repl-conn
    secretTemplate:
      key: dsn

  # service:
  #   type: LoadBalancer
  #   metadata:
  #     annotations:
  #       metallb.universe.tf/loadBalancerIPs: 172.18.0.150

  # primaryService:
  #   type: LoadBalancer
  #   metadata:
  #     annotations:
  #       metallb.universe.tf/loadBalancerIPs: 172.18.0.160

  # secondaryService:
  #   type: LoadBalancer
  #   metadata:
  #     annotations:
  #       metallb.universe.tf/loadBalancerIPs: 172.18.0.161

  metrics:
    enabled: false

  nodeSelector:
    kubernetes.io/arch: amd64
