apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-nvme-3-replicas
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "120"
  fromBackup: ""
  diskSelector: "nvme"