apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-key-secret
  namespace: cert-manager
type: Opaque
stringData:
  # Configure your API Key or Credentials here...
  # ---
  # API Key:
  api-key: c8d993e133f03da03de4c471ded35f4089343
  # - or -
  # Token:
  # api-token: your-api-token
